name: lectures
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  image_picker: ^1.1.2
  permission_handler: ^11.0.1
  provider: ^6.0.5
  http: ^1.1.0
  flutter_stripe: ^11.0.0
  flutter_secure_storage: ^9.0.0
  firebase_core: ^2.0.0
  firebase_messaging: ^14.0.0
  flutter_local_notifications: ^17.0.0
  dgis_flutter: ^0.0.31
  geolocator: ^10.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.0
  badges: ^3.1.2
  url_launcher: ^6.2.5
dev_dependencies:
 

  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/launcher_icon.png